apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: {{ .Values.namespace.name }}
data:
  config.yaml: |
    global:
      correlationIdHeader: "X-Internal-Correlation-ID"

    server:
      port: 3000
      readTimeoutSeconds: 15
      writeTimeoutSeconds: 15

    logger:
      file: /home/nonroot/outputs/outputs.log
      level: debug

    mountebank:
      host: mountebank-svc
      health:
        port: 2525
        path: config/
      imposters:
        - name: list
          path: v1/planets
          port: 4545
        - name: earth
          path: v1/planet/earth
          port: 4548
        - name: jupiter
          path: v1/planet/jupiter
          port: 4550
        - name: mars
          path: v1/planet/mars
          port: 4549
        - name: mercury
          path: v1/planet/mercury
          port: 4546
        - name: neptune
          path: v1/planet/neptune
          port: 4553
        - name: pluto
          path: v1/planet/pluto
          port: 4554
        - name: saturn
          path: v1/planet/saturn
          port: 4551
        - name: uranus
          path: v1/planet/uranus
          port: 4552
        - name: venus
          path: v1/planet/venus
          port: 4547