{{- if .Values.main.ingress.contour.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contour-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  ingressClassName: {{ .Values.main.ingress.contour.ingressClassName }}
  rules:
    - host: {{ .Values.main.ingress.host }}
      http:
        paths:
          {{- include "main.ingress.contour.matchers" . | indent 10 }}
  {{- end -}}