{{- if .Values.main.ingress.contour.enable }}
{{- $ingressName := "contour-ingress" }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    name: {{ $ingressName }}
    version: {{ .Values.global.version }}
spec:
  ingressClassName: {{ .Values.main.ingress.contour.ingressClassName }}
  rules:
    - host: {{ .Values.main.ingress.host }}
      http:
        paths:
          {{- include "main.ingress.contour.matchers" . | indent 10 }}
    - host:  {{ .Values.main.ingress.grpc.host }}
      http:
        paths:
          {{- include "main.ingress.contour.grpc" . | indent 10 }}
  {{- end -}}