{{- if .Values.main.ingress.istio.enable }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mountebank-gateway
  namespace: mountebank
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "mountebank.local.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mountebank-vs
  namespace: mountebank
spec:
  hosts:
    - "mountebank.local.io"
  gateways:
    - mountebank-gateway
  http:
    - match:
          {{- include "main.ingress.istio.matchers" . | indent 8 }}
      route:
        - destination:
            port:
              number: {{ .Values.main.ingress.port }}
            host: {{ template "main.service.fullname" . }}
{{- end -}}