{{- if .Values.main.ingress.istio.enable }}
{{- $ingressName := "mountebank-gateway" }}
{{- $vsName := "mountebank-vs" }}

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $ingressName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    name: {{ $ingressName }}
    version: {{ .Values.global.version }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "mountebank.local.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $vsName }}
  namespace: {{ .Values.namespace.name }}
spec:
  hosts:
    - {{ .Values.main.ingress.host }}
  gateways:
    - {{ $ingressName }}
  http:
    - match:
          {{- include "main.ingress.istio.matchers" . | indent 8 }}
      route:
        - destination:
            port:
              number: {{ .Values.main.ingress.port }}
            host: {{ template "main.service.fullname" . }}
{{- end -}}