apiVersion: v1
kind: Service
metadata:
  name: {{ template "main.service.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    name: {{ template "main.service.fullname" . }}
    version: {{ .Values.global.version }}
  annotations:
    projectcontour.io/upstream-protocol.h2c: {{ .Values.main.ingress.grpc.backend.port | quote }}
spec:
  type: {{ .Values.main.service.type }}
  selector:
    name: {{ template "main.pod.fullname" . }}
    version: {{ .Values.global.version }}
    {{- include "main.service.port.range" . | indent 2 }}
